apiVersion: ENC[AES256_GCM,data:bBI=,iv:w95BWJA/n+6MVLnMOz9pSuZRtXJX6BhIYwijdDfF4T8=,tag:aK40nTQXQVwcglC4hyoV+A==,type:str]
kind: ENC[AES256_GCM,data:DaMSIf4H,iv:1icaqskns3+ObxGEUJzAjMBMOSdi9GR9dZCm6nF9pX0=,tag:BY5Ygp06O01BMs+3jGtKAw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:gWJkV7jeQjJX06bSkgrxXL6h9So=,iv:IAZU4aj90bxftMoDiiFO9QP/5ADcXjPF/rW+F5hhKj8=,tag:xwpc2f2pJwmf8mnzy7nfFg==,type:str]
  namespace: ENC[AES256_GCM,data:uBFS5H0i5zuJAWw=,iv:kEa+vRtMAgKEX6VsOmrtHDhsHsqKoRWFPJEAPzi6PDA=,tag:peaK2hrNgAr4WgCEln466Q==,type:str]
type: ENC[AES256_GCM,data:sn3xb9zH,iv:y6KDevZiOCRJRe6QrduN4FxCoNV3vxWQgcKqqI2P5kY=,tag:Vf32VUnGEUOzcFQnffeehw==,type:str]
data:
  AERODATABOX_API_KEY: ENC[AES256_GCM,data:cLUZJgug2SDhGrrVEocoVOFpuX5yi62tmxQdF5vVedSD0cP6rDrVRqXo4m130gCCYBXazA7VLQVPixwvgVgCT3baZik=,iv:tfaXd/VLIAIlzjxxSbXORw0fSRbTyc7c2NM+qgDh/Uk=,tag:01d+v8vP0n4hw5QsvAPpCg==,type:str]
  IGNV_API_KEY: ENC[AES256_GCM,data:ss3OJ3XknkA1SMTrj5a9KrJRA3AG60PThEvJYYEjoGY586M3giV7KNIoErEeY8RBFwrN7g==,iv:/9b9J+wVVPz0ErN0FhoZ8CXOw/DApxZCZEUKcSGDZ8M=,tag:MDo6zbXmTA7UUof3h/AB5Q==,type:str]
sops:
  age:
    - enc: '-----BEGIN AGE ENCRYPTED FILE-----

        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU0hXdEgwMnNDUUxkSy84

        NnJpMjVzMTYxZk5sdmlNcENVc24yNkc1ZzI0CmdtVGgyT3kyK2Vjc0lsSnFqL2Z4

        dEJqY1dFWE9oVUNQOEV6SnR3bkxUT2sKLS0tIDlSQ1ZVcjE0eXVjeVovVFdjWnFK

        RGJhMnF5Ymx1TDJ6dVlsREJhcjkyYm8K/XOgpTp1XV0i8ViWoXSnIAJ38DSNNGGQ

        FSMIYI+QeFiyVo5iq/4hivk8uicuVc3PY1Z/DACFGBYgZbUae415sA==

        -----END AGE ENCRYPTED FILE-----

        '
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  lastmodified: '2026-09-02T15:52:51Z'
  mac: ENC[AES256_GCM,data:m3EAkL6omuVYOGqFKiDi2+hiTWlQJ/Vubip0AeXcv+LvybENJ+mITClyQh8sJDozzDvrfg1MosQYsfxdR2oIzwpqSOGqZ353Xzn+Yyr1uu5qs4/9GI7gOHo8ExprXpozXMCeCzDCCB2qdGGTVec00cWmazfC0L6CiQj87/Vh0v4=,iv:U5jxxS0mCFQQFAGkPOudsohntFkYo44yFWs1IPgo7zw=,tag:ZEIH3o8z5Oru9vyHaWaJlg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
