apiVersion: v1
kind: Secret
metadata:
    name: travelagent-api-keys
    namespace: travelagent
type: Opaque
data:
    AERODATABOX_API_KEY: ENC[AES256_GCM,data:Wvg8DRB+WxAp1S1XV8kJ0bhygfEu5WKn203qR6jADDCPuAkNQWGCKuu7QQkwyalcUg8S8+b19BAu3uGo1rYcaPJ2S8A=,iv:2c3hjeeaUcUFJuTRQUXgjg7YtTOizTPR2wWrzsHm9uU=,tag:YCNk4AOhA0IgLxhzltwbqg==,type:str]
    IGNV_API_KEY: ENC[AES256_GCM,data:MrRLKABbyCBWD3noHwU8pE9NYDHa/KACmw97ha1y/743avRL7NyjqnxEOvplHmodIB4ysw==,iv:GJuBK20VTGug7fWPLcl+73gKw9/T3O0+VR7yoxInbd8=,tag:09nfCHyDRX4roJLuf/eiUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K0JkbExKclh1Y0wrNC9O
            cXI5UWhHYitVN0tUTndybkkwWVFPaG5PQ0U0ClNxSjhyTjl5QzZVUVRuTHp0SG1u
            RWl4K0JtUm4zTUhISjEvWXg1ci8yWEUKLS0tIGJLRW9POVNETXZvMkhPcytiSEFY
            TEd0Y1h3eVIrQkw2Mlp0UFNrQ3hHWncKM7Ay0XdKvnIZTAa/UKYFBwcK1wyiMCVA
            +G77mQeHvqjFoYFHY1mb6KxIb+hrOwQSdAZQZwjdmVq5T1gn6N7hpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T20:50:02Z"
    mac: ENC[AES256_GCM,data:TiPbBmcrXsemc1OQm8BokN2yvAxNy7le149m51ccuX8W3PvYUw9sAKf9FU5XTTGMKVHEL1/UIOg8DOAsM+N9bANwWJWgz9l6oqGxwPu+NPZA4JrK7qXkvxxc4RQPmb+Z5ykt5FwtGnyc1mApZoGCX404k6Bs0mhEguYF8E02B6Q=,iv:6IlySu3HeYjWn8bDv4SRsGN//v0J5azBtSR/ksTKnU8=,tag:ipQMIztzVaQWiFVWEKlJag==,type:str]
    version: 3.13.3
