apiVersion: v1
kind: Secret
metadata:
      name: ghcr-secret
      namespace: travelagent
type: kubernetes.io/dockerconfigjson
data:
      .dockerconfigjson: ENC[AES256_GCM,data:cF2tbchLA2ev5iXqO2o/NtWo0BojjSFe0RaDPK7FffABZN5xkwLvS55oUXDODEIq7VhCcwJLImrwGXRVIaDO5C9j5aNzlNhLnjwgfdwFnwePzWRf6RnxFo5MZiHjzduo3SSFDUFTn7XB4cFW1NgajsLlrL4TkiZZwbqaNy/9EWcLSihS8lBjY1c/O/E=,iv:pz4WHCFPuZMlJzPMkOV5GwW+aUId1WL3bNNvDZ/Yg54=,tag:ILyIUbo2qrUEvw8RC5EKmg==,type:str]
sops:
      age:
            - enc: "-----BEGIN AGE ENCRYPTED FILE-----

                    YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR3Uzd1VaV1p1dm1ZejQ5

                    Z3dwam9USTJhS0VsTlJNMno3QmlKN2MwbGxJCjNtR0lmSzZtdnpnMnoreHlFeS9D

                    U3FrUTRlMVU0dm1qa1EwcXFQSXhScFkKLS0tIFpZYVRac3cwcFZ0MWNmSjBvdS8y

                    ZDJ6YTRUaXF1TGhHN29SWFNLemRxSGsKiy2S12JMHBpP/kAMhqKD8vulG2DGJzmz

                    3lqwJ6B9jNVPrV8KzdmgM5YreloKgrNtKPT91/0ZnGw0vLccPUDB5g==

                    -----END AGE ENCRYPTED FILE-----

                    "
              recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
      encrypted_regex: ^(data|stringData)$
      lastmodified: "2026-09-02T07:50:44Z"
      mac: ENC[AES256_GCM,data:cJjTKV7+lp2XHFgNbbsBVJyYfvQzsUHrIfDCf9F3yyKl2OVYcKMuohFtEsvueotaTFd4ezip6GCzBT+b7tW9Wt/E4r9ANyAHEGCcKzMvBjnicnzgdeMtVIhJj/zBPMnDapRTkKHL2Dn9GZQq5hL8Ew5uaxDXJZ58gjYpBH69xTg=,iv:x8PDIi7+WswsrjLR53Gr8EXKm6pxkYHqC2wUqR/jwLI=,tag:uAHGVqUA78BCrB5ZQ0fvXg==,type:str]
      version: 3.13.3
